import type { Metadata } from "next"
import { GeistSans } from "geist/font/sans"
import { Toaster } from "sonner"

import "@/shared/styles/global.css"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${GeistSans.className}`}>
				{children}
				<Toaster richColors />
			</body>
		</html>
	)
}
